### PR TITLE
Support for async via `before` callback optionally defined in steps[]

### PR DESCRIPTION
**Pull request by buwilliams**
Today with vue-tour there is no way to:
- halt a nextStep(), previousStep(), or start() if UI isn't ready
- do async UI setup work for complex single-page applications between steps

This PR addresses these limitations by:
- allowing users to optionally specify a `before()` callback in `steps`
- PR is backwards compatible, it will only affect those using the new `before()` callback so all existing implementations will continue to work

The callback must return a promise. If the promise is rejected then vue-tour will not move to the next step. If the promise is accepted then it will move on to the next step.

Additionally included in this PR:
- several fixes to existing tests
- ensure the test framework runs the specs because it currently does not
- updated README to support `before()`
- new unit tests for `before()`
- commit messages which conform to contributing docs

### CODE REVIEW

**Comment by buwilliams** [comment]
Bump. What's the status?

**Comment by LevShipulin** [comment]
Also waiting for this functionality! @mmorainville plaese review :)

**Comment by mmorainville** [comment]
Hi,

Sorry for the delay, we wanted to take some time to improve the delivery process of vue-tour. We have done this (and incorporate the highlight feature in the meantime) and we are now ready to review all other PRs including this one.

**Comment by algomax** [comment]
It would be really great, if this merge request could be completed. Being able to handle asynchronous situations using before() is really critical. Thank you!

**Comment by nullablebool** [comment]
+1 It be great to get this PR in.

**Comment by ABartelt** [comment]
+1 This is exactly what we are looking for right now

**Comment by mmorainville** [comment]
This has been merged and released in v1.5.0!
Thanks a lot to @buwilliams for his contribution!

**Pull request merged**
