### PR TITLE
Update to @popperjs/core

### PR DESCRIPTION
**Pull request by yuters**
The new version of Popper.js fixes a loooooot of issues with flex positioned elements and this small update basically fixed all my problems instantly.

I hope you can update your package soon, thanks :)

### CODE REVIEW

**Comment by glorat** [comment]
Thanks for doing this! I was also tempted to upgrade popper as I'm having placement difficulties I hoped were getting fixed in the latest popper. Hope maintainers can have a good look at this.

**Comment by Outpox** [comment]
Hey there sorry for the delay, I was planning to review this PR this week but couldn't make it.  
I hope we can merge and publish this quickly because this is really useful! I plan on working on this next week ;-)

**Comment by Outpox** [comment]
I've successfully tested this PR on local and I would really like to merge it quickly but since Popper is including breaking changes that impacts us we would also have to include these breaking changes.  
This is related to the `modifiers` property which used to be an object that is now an array.  

We are going to merge the 2 oldest PR in vue-tour 1.x and will release this in a new 2.x version.

**Comment by jprodrigues70** [comment]
Any updates?

**Comment by mmorainville** [comment]
Hi @jprodrigues70, it should be merged before the end of summer, we want to merge all other PRs before it as updating Popper will cause a breaking change for vue-tour (as the custom options will be different).

**Comment by ozanerturk** [comment]
any updates ?

**Comment by mmorainville** [comment]
Duplicate of https://github.com/pulsardev/vue-tour/pull/177 and https://github.com/pulsardev/vue-tour/pull/172 which have been merged.

**Pull request closed without merging**
