### PR TITLE
feat(highlight): add the possibility to highlight elements during the…

### PR DESCRIPTION
**Pull request by Art3miX**
… tour #48 #11

### CODE REVIEW

**Comment by Art3miX** [comment]
By mistake the last PR had some other stuff than the highlight feature, so i have closed it and did a new one with only the highlight changes.

**Comment by Outpox** [comment]
Hey there!
Thanks for splitting the PR apart. We've had a look already but we just need time to merge and deploy it, I'll try to do that next week ;-)

**Comment by rshm** [comment]
When will these changes be in master. I would like to use the highlight feature when I install the plugin using npm install and not go to a specific branch to have clean package.json. Really looking forward to it.

**Comment by stevenschemers** [comment]
Also wondering when this PR will be merged in. The highlight is a very useful feature.

**Comment by stevenschemers** [comment]
Also wondering when this PR will be merged into master. The highlight is a very useful feature.

**Comment by bartvanremortele** [comment]
Also looking for the highlight feature...

**Comment by mateuswetah** [comment]
#moveToMaster (no pressure but yes pressure) hehehe

**Comment by Kansukey** [comment]
Hi there!

I'm also interesting by this highlight feature, and I don't really want to fork or use the `develop` branch into a production app!

Is a merge into `master` planned ? :smile:

**Comment by shadowam** [comment]
Hello, any news on this? We are using this amazing plugin in production and would love this feature.

**Comment by Heziode** [comment]
up

**Comment by HZooly** [comment]
Hey guys, we are currently working on Vue Tour v2. This version will be deployed as soon as possible with this feature 😊

**Comment by clemjlt** [comment]
Awesome ! ☺️

**Pull request merged**
