### PR TITLE
Migrated Popperjs and fixed bluring issue.

### PR DESCRIPTION
**Pull request by smitpatelx**
- Now using `box-shadow` instead of `filter`
- Replaced `popper.js` with `@popperjs/core@^2.9.1`

### CODE REVIEW

**Comment by akempes** [comment]
@smitpatelx Thanks for your PR. The positioning issues I experienced are now fixed. The only issue I encountered is the missing arrow pointing to the element. (See attachment)
Screenshot 2021-03-19 at 10 08 44

**Comment by smitpatelx** [comment]
@akempes Yes I noticed that, and now its fixed.

**Comment by mmorainville** [comment]
Hi @smitpatelx,

Thanks for your contribution!
I'm looking to merge your PR but encountered a strange behavior with the arrows on my side, I'm debugging it now, will surely find something but in any case here it is:

image

The centering of the arrow seems a bit off and it's over the target element.
See this image of the current version (v1.6.0) for reference:

image

**Comment by smitpatelx** [comment]
@mmorainville 
I have fixed the offset issue.

**Comment by mmorainville** [comment]
Thanks @smitpatelx!
And I fixed the centering of the arrow. Everything is ready in this PR: https://github.com/pulsardev/vue-tour/pull/177/files.
But now I have some failing unit tests.
The behavior is a bit weird and must have something to do with the async behavior of the start method, but nothing changed in this PR regarding this... so I'm a bit confused.

```
 expect(wrapper.vm.currentStep).toEqual(-1)
 await wrapper.vm.start()
 expect(wrapper.vm.currentStep).toEqual(0)
```

This part is failing, which means that for the test the tour never starts (currentStep is always -1), but when I test myself, the tour starts normally and everything is ok. Seems to be failing just when testing, quite unexpected.
I've come across this page: https://vue-test-utils.vuejs.org/guides/testing-async-components.html but we seems to do everything correctly so...

**Comment by mmorainville** [comment]
Update: I managed to get them pass by using shallowMount instead of mount to mount the VTour component.
Not sure if it's really the right thing to do, but it works...

**Pull request merged**
